name: 删除releases，清理旧版本
on:
# 定时触发开启开始编译(把下面两个#去掉开启,时间设置请看定时开启编译说明)
  schedule:
   - cron: 40 23 * * 4

#40 23 * * 4 解释如下：
#40 23：表示小时和分钟，即23时40分，也就是每天的午夜（23:40）UTC时间
#* *：表示每个月的每一天。
#4：表示星期几，其中数字4代表星期四。
#在每个星期四的午夜（也就是星期四的晚上）执行任务。

  workflow_dispatch:

jobs:
  del_releases:
    runs-on: Ubuntu-22.04
    name: delete-releases-runs
    steps:
    
      - name: 删除releases，清理旧版本
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: ${{ github.repository }}
          keep_latest: 0
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
